name: radar-card-test
services:
  test-homeassistant:
    container_name: ha-radar-card-test
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ../dist:/config/www/dist:ro
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
    ports:
      - '8133:8123'
